/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BloodRequestService } from "../bloodRequest.service";
import { BloodRequestCreateInput } from "./BloodRequestCreateInput";
import { BloodRequest } from "./BloodRequest";
import { BloodRequestFindManyArgs } from "./BloodRequestFindManyArgs";
import { BloodRequestWhereUniqueInput } from "./BloodRequestWhereUniqueInput";
import { BloodRequestUpdateInput } from "./BloodRequestUpdateInput";

export class BloodRequestControllerBase {
  constructor(protected readonly service: BloodRequestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BloodRequest })
  async createBloodRequest(
    @common.Body() data: BloodRequestCreateInput
  ): Promise<BloodRequest> {
    return await this.service.createBloodRequest({
      data: data,
      select: {
        bloodType: true,
        createdAt: true,
        fulfilled: true,
        id: true,
        quantity: true,
        requestDate: true,
        requester: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [BloodRequest] })
  @ApiNestedQuery(BloodRequestFindManyArgs)
  async bloodRequests(@common.Req() request: Request): Promise<BloodRequest[]> {
    const args = plainToClass(BloodRequestFindManyArgs, request.query);
    return this.service.bloodRequests({
      ...args,
      select: {
        bloodType: true,
        createdAt: true,
        fulfilled: true,
        id: true,
        quantity: true,
        requestDate: true,
        requester: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BloodRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async bloodRequest(
    @common.Param() params: BloodRequestWhereUniqueInput
  ): Promise<BloodRequest | null> {
    const result = await this.service.bloodRequest({
      where: params,
      select: {
        bloodType: true,
        createdAt: true,
        fulfilled: true,
        id: true,
        quantity: true,
        requestDate: true,
        requester: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BloodRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBloodRequest(
    @common.Param() params: BloodRequestWhereUniqueInput,
    @common.Body() data: BloodRequestUpdateInput
  ): Promise<BloodRequest | null> {
    try {
      return await this.service.updateBloodRequest({
        where: params,
        data: data,
        select: {
          bloodType: true,
          createdAt: true,
          fulfilled: true,
          id: true,
          quantity: true,
          requestDate: true,
          requester: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BloodRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBloodRequest(
    @common.Param() params: BloodRequestWhereUniqueInput
  ): Promise<BloodRequest | null> {
    try {
      return await this.service.deleteBloodRequest({
        where: params,
        select: {
          bloodType: true,
          createdAt: true,
          fulfilled: true,
          id: true,
          quantity: true,
          requestDate: true,
          requester: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
