/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FacilityService } from "../facility.service";
import { FacilityCreateInput } from "./FacilityCreateInput";
import { Facility } from "./Facility";
import { FacilityFindManyArgs } from "./FacilityFindManyArgs";
import { FacilityWhereUniqueInput } from "./FacilityWhereUniqueInput";
import { FacilityUpdateInput } from "./FacilityUpdateInput";
import { BloodTransfusionFindManyArgs } from "../../bloodTransfusion/base/BloodTransfusionFindManyArgs";
import { BloodTransfusion } from "../../bloodTransfusion/base/BloodTransfusion";
import { BloodTransfusionWhereUniqueInput } from "../../bloodTransfusion/base/BloodTransfusionWhereUniqueInput";

export class FacilityControllerBase {
  constructor(protected readonly service: FacilityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Facility })
  async createFacility(
    @common.Body() data: FacilityCreateInput
  ): Promise<Facility> {
    return await this.service.createFacility({
      data: data,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Facility] })
  @ApiNestedQuery(FacilityFindManyArgs)
  async facilities(@common.Req() request: Request): Promise<Facility[]> {
    const args = plainToClass(FacilityFindManyArgs, request.query);
    return this.service.facilities({
      ...args,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Facility })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async facility(
    @common.Param() params: FacilityWhereUniqueInput
  ): Promise<Facility | null> {
    const result = await this.service.facility({
      where: params,
      select: {
        address: true,
        contactNumber: true,
        createdAt: true,
        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Facility })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFacility(
    @common.Param() params: FacilityWhereUniqueInput,
    @common.Body() data: FacilityUpdateInput
  ): Promise<Facility | null> {
    try {
      return await this.service.updateFacility({
        where: params,
        data: data,
        select: {
          address: true,
          contactNumber: true,
          createdAt: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Facility })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFacility(
    @common.Param() params: FacilityWhereUniqueInput
  ): Promise<Facility | null> {
    try {
      return await this.service.deleteFacility({
        where: params,
        select: {
          address: true,
          contactNumber: true,
          createdAt: true,
          id: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bloodTransfusions")
  @ApiNestedQuery(BloodTransfusionFindManyArgs)
  async findBloodTransfusions(
    @common.Req() request: Request,
    @common.Param() params: FacilityWhereUniqueInput
  ): Promise<BloodTransfusion[]> {
    const query = plainToClass(BloodTransfusionFindManyArgs, request.query);
    const results = await this.service.findBloodTransfusions(params.id, {
      ...query,
      select: {
        bloodType: true,
        createdAt: true,

        facility: {
          select: {
            id: true,
          },
        },

        id: true,
        patient: true,
        quantity: true,
        transfusionDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bloodTransfusions")
  async connectBloodTransfusions(
    @common.Param() params: FacilityWhereUniqueInput,
    @common.Body() body: BloodTransfusionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bloodTransfusions: {
        connect: body,
      },
    };
    await this.service.updateFacility({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bloodTransfusions")
  async updateBloodTransfusions(
    @common.Param() params: FacilityWhereUniqueInput,
    @common.Body() body: BloodTransfusionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bloodTransfusions: {
        set: body,
      },
    };
    await this.service.updateFacility({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bloodTransfusions")
  async disconnectBloodTransfusions(
    @common.Param() params: FacilityWhereUniqueInput,
    @common.Body() body: BloodTransfusionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bloodTransfusions: {
        disconnect: body,
      },
    };
    await this.service.updateFacility({
      where: params,
      data,
      select: { id: true },
    });
  }
}
